version: '3'
services:
    nginx:
        build: ./nginx
        ports:
            - "5000:5000"
            - "80:8080"
    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/usr/local/apache2/htdocs/
            

    flask:
        # Путь до Dockerfile
        build: ./backend
        # Имя для создаваемого контейнера
        container_name: backend-flask
        # Создание переменных окружения в контейнере
        environment:
            # для отладки (при запуске в релиз убрать!)
            - FLASK_DEBUG=development
            ## Позволяет отслеживать процесс работы приложения в командной строке
            - PYTHONUNBUFFERED=True
            ##
            # Перезапускаем сервис в случае падения 
        restart: on-failure
        # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
        # директории ./backend, появятся в директории контейнера /backend
        volumes:
            - ./backend:/backend
        # Открываем порт в контейнер
        # Порт, который будет смотреть наружу : порт который используется внутри контейнера

        command: gunicorn main:"create_flask_app()" -b 0.0.0.0:5000 --reload
        ports:
            - "5001:5000"